[package]
name = "easybuffers"
version = "1.0.1"
authors = ["SleepPerformer <337990443@qq.com>"]
description = "Faster serialization and deserialization than protobuf."
license = "MIT/Apache-2.0"
repository = "https://github.com/SleepPerformer/easybuffers"

[dependencies]
time = "*"